### ISSUE TITLE
Seems to not work on Win10

### ISSUE THREAD

**Issue by Xuerian** [nedrysoft/pingnoo#57] opened 2021-04-16 02:25 UTC
Installed: Pingnoo.2021.04.08-develop.x86_64.exe

Starts, adds 1.1.1.1 tab when Start is clicked, but shows nothing for a long time then shows 63 timeouts. traceroute traces the route fine.

Didn't seem to work for 8.8.8.8 either.

**Comment by fizzyade** [comment] 2021-04-16 06:24
Do you have windows firewall (or a third party) enabled?

**Comment by Xuerian** [comment] 2021-04-16 08:34
I do have Windows Firewall enabled.

I added a rule allowing Pingnoo.exe and the behavior didn't change.

**Comment by fizzyade** [comment] 2021-04-17 09:48
Sorry, I'm really unwell at the moment.  Can you try temporarily disabling windows firewall and retesting.

**Comment by big610** [comment] 2021-04-18 18:32
I didn't want to bother, willing to wait patiently, but I'm seeing the "not work" on macs. Agree & thanks to Xuerian for identification. 

Pingnoo.2021.04.08-develop.x86_64.dmg
Never able to run & show anything, disables entire internet connection., unable to re-connect. To fix re-boot.
Keeping this version installed to test notification for an update from 3rd party software.

Pingnoo.2021.03.21-develop.x86_64.dmg
Running fine, minus the ability for 3rd party software to identify a new version.
Will use this version, when needed, then swap back versions.

I tested multiple times back & forth between versions, confirming. 
No mac firewall, 3rd party, enabled.

**Comment by fizzyade** [comment] 2021-04-18 23:45
@big610 My development environment is macOS, I'm not seeing any issues and I obviously run it a lot.

If you can produce a repeatable case where it doesn't work, then please let me know and I can try to reproduce it, I just downloaded and installed 2021.04.08 and ran it and it worked as expected.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/55795671/115165839-c204a900-a0a7-11eb-819e-c0d760996024.png">

What macOS version?  Intel/M1?

@Xuerian I have finally got around to providing an ICMPAPI ping engine for Windows.  Can you download and try the test release (I've included installers and portable edition zip files).  Ensure you select ICMPAPI as the ping engine, I suspect (hope) that this will work for you - although it currently only supports IPv4, I need to make some minor changes for it to add IPv6 support.  I'm hoping that with ICMPAPI it may play nicer with the Windows firewall as the application doesn't need to use raw sockets.

**Comment by Xuerian** [comment] 2021-04-19 00:13
Sorry to hear that you're unwell. Please don't feel pressured to work on this.

Disabling the firewall did let it work - partially. It didn't (compared to tracert) identify the first three hops.

As far as 2021.04.19-feat/icmpapi, I'm only seeing the ICMP Socket engine.

![image](https://user-images.githubusercontent.com/2985/115166676-67a52180-a082-11eb-8c73-9d5cfb19c36a.png)

I'd be down for raw socket requirements if you could implement UDP traceroute on windows somehow, that's a pretty rate thing at the moment. But, I assume it's that way for a reason.

**Comment by big610** [comment] 2021-04-19 00:27
Intel macOS 10.15.7 Catalina.
Clicking the start button: 20 seconds to connections with 03.21. 45 seconds till I lose Internet Connection with 04.08, then a fight to get my unit to re-boot, to get the Internet Connection back after Restart.
[pingnoo.2021.03.21 2 copy.pdf](https://github.com/nedrysoft/pingnoo/files/6332527/pingnoo.2021.03.21.2.copy.pdf)
![Pingnoo 2021 04 08](https://user-images.githubusercontent.com/35133409/115167146-0ebd9500-a052-11eb-8b1b-90ebcd66048b.png)

My Windows units or my secondary & third units. I need C+++ for Portable. VCRUNTIME140_1.dll was not found Microsoft Visual C++ 2015 - 2019, I have 2017, debating which download to use and I need to update Versions of Windows 10.

**Comment by fizzyade** [comment] 2021-04-19 10:21
I tried the portable x86_64 version on a fresh installation of Windows 10 and it ran without any problems.  The x86 version is broken when using the ICMPAPI ping engine and I think I know why.

The installer I created last night has bundled the wrong ICMPAPI ping engine, it's the wrong size for some reason - I have no idea how this has happened, but I'm pretty sure it's incorrectly installed the x86 version of that DLL rather than the x86_64 version.

If you download the x86_64 portable edition and then copy the ICMPAPIPingEngine.dll file from the Components folder into the Components folder where you installed the software and then run pingnoo, you should have ICMPAPI as an option.  On my fresh Windows install it works with that ping engine without having to modify the firewall.

Alternatively, just download the x86_64 portable version and run that.

I will try to fix these issues tonight.

**Comment by fizzyade** [comment] 2021-04-19 16:01
Also, please don't be afraid to report stuff!  I may not be able to fix stuff straight away, but if I don't know that there's a problem then I just assume everything is OK and that there are no problems.

Without reports like these, I can't fix your problems, so I appreciate them!

This particular issue (the original one) forced me to go back and finish up support for ICMPAPI, I fleshed out the basic plugin right at the start but never finished it and it wasn't a major priority.  Things had changed quite a bit from when I originally wrote the code to now, so I'd been avoiding doing it because the code wouldn't compile and would need quite a lot of changes to match the current interfaces.

> Disabling the firewall did let it work - partially. It didn't (compared to tracert) identify the first three hops.

This is probably because the hops took longer than a second to respond?  Can you give me a copy of the output from traceroute and a screenshot of the the pingnoo result.  (You can obfuscate your public IP in the data)

> I'd be down for raw socket requirements if you could implement UDP traceroute on windows somehow, that's a pretty rate thing at the moment. But, I assume it's that way for a reason.

This is the plan, the software is architected to allow functionality like this to be added easily.

**Comment by Xuerian** [comment] 2021-04-19 19:39
I turned off the firewall (A restart isn't necessary) and the base ICMP trace worked fine this time. Could have been a hiccup in my connection last time.

The ICMPAPI engine worked fine as well with firewall on when copied from the portable package.

**Comment by fizzyade** [comment] 2021-04-19 20:07
> I turned off the firewall (A restart isn't necessary) and the base ICMP trace worked fine this time. Could have been a hiccup in my connection last time.
> 
> The ICMPAPI engine worked fine as well with firewall on when copied from the portable package.

I've just pushed the latest binaries to github. 

https://github.com/nedrysoft/pingnoo/releases/tag/2021.04.19-feat%2Ficmpapi

Same version number, but different git commit hash - the hash is now displayed in the title bar of the software, once installed you should see 7cbed8b, if you see that, then all is golden and you've got the new release installed.

The installer fixes the issue where it installed the wrong ICMPAPI ping engine dll.

I've checked that:

- the 64 bit portable works correctly on a fresh, clean Windows 10 64-bit installation.
- the 32 bit portable works correctly on a fresh, clean Windows 10 64-bit installation.
- the installer correctly installs the 64-bit version and it works correctly on a clean Windows 10 64-bit installation.
- the 32 bit portable works correctly on a fresh, clean Windows 10 32-bit installation.
- the installer correctly installs the 32-bit version and it works correctly on a clean Windows 10 32-bit installation.

I checked that the ICMPAPI ping engine was available on each platform and tested it and confirm it works fine for me.  It's still work in progress, I need to do more work on it, but the base is there, at least for IPv4 - it currently won't work for IPv6 as I need to switch the API calls.

**Comment by fizzyade** [comment] 2021-04-19 23:48
@big610 

> Intel macOS 10.15.7 Catalina.
> Clicking the start button: 20 seconds to connections with 03.21. 45 seconds till I lose Internet Connection with 04.08, then a fight to get my unit to re-boot, to get the Internet Connection back after Restart.

I just downloaded 2021.04.08 from GitHub and tested on a clean installation of macOS 10.15.7 and it worked without any issues.  I am going to leave it running overnight.

**Comment by fizzyade** [comment] 2021-04-20 20:22
I've pushed code (but not created binaries) which adds IPv6 support for the ICMPAPI ping engine, in addition, the target parser has been re-written to correctly identify IPv4, IPv6 and hostnames in conjunction with the radio buttons.

I'm going to close this issue as the original issue is solved.

**Closed as completed by fizzyade** 2021-04-20 20:22 UTC
