### ISSUE TITLE
Minimum macOS supported version?

### ISSUE THREAD

**Issue by cotwitch** [nedrysoft/pingnoo#27] opened 2021-03-04 09:38 UTC
Hi!
I'm trying pingnoo for macOS (dmg from release page https://github.com/nedrysoft/pingnoo/releases/tag/2021.02.17-develop).

I currently have macOS Mojave 10.14.6 (with all available updates installed), but unfortunately, when I execute pingnoo I'm getting following "little-bit uncertain" error:

![image](https://user-images.githubusercontent.com/10708898/109941274-45726280-7cd3-11eb-91a3-dd7f825b6fb5.png)

So, I would like to kindly ask you, which macOS version is the minimum to execute pingnoo?

PS: Btw, I'm just curious if the name `nedrysoft` is abstracted from `Dennis Nedry` from the Jurrasic Park? 🤩

**Comment by fizzyade** [comment] 2021-03-04 12:41
Thie minimum should be High Sierra, I will have to check what is happening, I'm on Big Sur.  I'll have to set up a High Sierra VM to see what is going on.

**Comment by djfinch** [comment] 2021-03-04 12:57
The minimum is ... Big Sur ... :)
![image](https://user-images.githubusercontent.com/13107713/109967246-795c8080-7cf1-11eb-92ef-60c2cd6ad3fc.png)

**Comment by fizzyade** [comment] 2021-03-04 19:12
> The minimum is ... Big Sur ... :)
> ![image](https://user-images.githubusercontent.com/13107713/109967246-795c8080-7cf1-11eb-92ef-60c2cd6ad3fc.png)

Urgh.  That's probably the cause of the issue.  It's dependencies are on Qt which currently only supports high sierra or later, but I think I've probably just set the application plist to the wrong version, I'm going to have a look now.  I was just copying High Sierra to my other mac which has VMware on it to so I could try, but I suspect I won't need to.

Thanks

**Comment by fizzyade** [comment] 2021-03-04 19:15
os it's compiling against the wrong version of macOS.  Sorry, I'll fix this.

**Comment by fizzyade** [comment] 2021-03-04 19:59
It should be fixed, I'm just scheduling the build and will then push the binaries.

**Comment by fizzyade** [comment] 2021-03-04 22:37
@djfinch @cotwitch I have created a new release, *I hope it's fixed now*.

**Comment by jonathand864** [comment] 2021-03-05 08:39
Hello, i have a 10.13.6 mac version and the last released fixed the issue which stopped me from launching the app but now the app crash as soon as i launch it.

**Comment by fizzyade** [comment] 2021-03-05 08:45
> Hello, i have a 10.13.6 mac version and the last released fixed the issue which stopped me from launching the app but now the app crash as soon as i launch it.

I will install high sierra in a VM so I can see what is going on.

**Comment by fizzyade** [comment] 2021-03-05 13:31
I have added an 2021.03.05-develop release which is macOS only and fixes the reported issue.

Somehow the application ended up with a mix of Qt 5.15.0 and 5.15.2 which resulted in a crash (this could be seen if launching from the terminal, when launching from the GUI you would get the crash with no real information)

Please note, there are some icons that have the wrong colour in light mode.  I will fix this, altso the colours seem to default to blue instead of green on the latency graphs, I will look into this as well.

**Comment by cotwitch** [comment] 2021-03-05 13:56
Confirming, version `2021.03.05-develop` is now working correctly on `10.14.6` ✅ Thanks a lot 👍

**Closed as completed** 2021-03-05 13:56 UTC
Labels: bug

**Comment by jonathand864** [comment] 2021-03-05 14:16
Perfect, version 2021.03.05-develop is working on 10.13.6 

Thank you fizzyade !

**Comment by fizzyade** [comment] 2021-03-05 14:33
I'm a bit unwell at the moment, but I will take a look over the weekend and fix the incorrect icon colours, I use dark mode and I must have forgotten to set the icon colour appropriately.  It's minor though.

**Comment by fizzyade** [comment] 2021-03-05 14:37
@cotwitch @jonathand864 @djfinch If you feel like giving any feedback I will happily listen to them.  I've reached the point where the base application is all there, now it's on to expanding the app, I need to add jitter graphs per hop.

**Comment by djfinch** [comment] 2021-03-05 19:31
488c2b7 Fixed the issue. Everything works well so far. Latest Catalina (10.15.7). Thanks!
![Screenshot 2021-03-05 at 20 29 35](https://user-images.githubusercontent.com/13107713/110164384-95dfe200-7df1-11eb-8568-9e59d198730a.jpg)

**Comment by fizzyade** [comment] 2021-03-05 19:39
Awesome.  I am going to fix a few things I've seen from this bug report so thanks to everybody for providing feedback that allowed me to find the source of the problems.
